# Generated by Django 3.0.3 on 2020-03-04 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_admin', models.BooleanField(default=False)),
                ('is_system_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_school_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_teacher', models.BooleanField(blank=True, default=False, null=True)),
                ('is_student', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schools.School', verbose_name='school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded files/school/teachers')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('academic_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('emergency_contact1', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact2', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded files/school/students')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.IntegerField(blank=True, null=True)),
                ('mother_phone', models.IntegerField(blank=True, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('emergency_contact1', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact2', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('father_annual_income', models.IntegerField(blank=True, null=True)),
                ('mother_annual_income', models.IntegerField(blank=True, null=True)),
                ('previous_school_info', models.TextField(blank=True, max_length=255, null=True)),
                ('class_of_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_admission', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
