export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


// COUNTRY
export const GET_COUNTRY_LIST_START = "GET_COUNTRY_LIST_START";
export const GET_COUNTRY_LIST_FAIL = "GET_COUNTRY_LIST_FAIL";
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS";

// export const DELETE_STUDENT_START = "DELETE_STUDENT_START";
// export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";
// export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";

// export const UPDATE_STUDENT_START = "UPDATE_STUDENT_START";
// export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";
// export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// export const GET_STUDENT_DETAIL_START = "GET_STUDENT_DETAIL_START";
// export const GET_STUDENT_DETAIL_FAIL = "GET_STUDENT_DETAIL_FAIL";
// export const GET_STUDENT_DETAIL_SUCCESS = "GET_STUDENT_DETAIL_SUCCESS";

// export const STUDENT_FORM_START = "STUDENT_FORM_START";
// export const STUDENT_FORM_FAIL = "STUDENT_FORM_FAIL";
// export const STUDENT_FORM_SUCCESS = "STUDENT_FORM_SUCCESS";


// TEACHER
export const GET_USER_LIST_START = "GET_USER_LIST_START";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const GET_USER_DETAIL_START = "GET_USER_DETAIL_START";
export const GET_USER_DETAIL_FAIL = "GET_USER_DETAIL_FAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";


// SCHOOL
export const GET_SCHOOL_LIST_START = "GET_SCHOOL_LIST_START";
export const GET_SCHOOL_LIST_FAIL = "GET_SCHOOL_LIST_FAIL";
export const GET_SCHOOL_LIST_SUCCESS = "GET_SCHOOL_LIST_SUCCESS";

export const DELETE_SCHOOL_START = "DELETE_SCHOOL_START";
export const DELETE_SCHOOL_FAIL = "DELETE_SCHOOL_FAIL";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";

export const UPDATE_SCHOOL_START = "UPDATE_SCHOOL_START";
export const UPDATE_SCHOOL_FAIL = "UPDATE_SCHOOL_FAIL";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";

export const GET_SCHOOL_DETAIL_START = "GET_SCHOOL_DETAIL_START";
export const GET_SCHOOL_DETAIL_FAIL = "GET_SCHOOL_DETAIL_FAIL";
export const GET_SCHOOL_DETAIL_SUCCESS = "GET_SCHOOL_DETAIL_SUCCESS";

export const CREATE_SCHOOL_START = "CREATE_SCHOOL_START";
export const CREATE_SCHOOL_FAIL = "CREATE_SCHOOL_FAIL";
export const CREATE_SCHOOL_SUCCESS = "CREATE_SCHOOL_SUCCESS";





// Just To Avoid errors
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
